import LayoutProvider from "@/components/LayoutProvider";
import "./globals.css";
import "./../stylesheets/commonClasses.css";
import "./../stylesheets/antdOverride.css";
import "./../stylesheets/layout.css";
import "./../stylesheets/loader.css";
import ReduxProvider from "@/components/ReduxProvider";
import { Metadata } from "next";

export const metadata= {
  title: "JobSeekr",
  description: "Generated by create next app",
  icons:{
    icon: ['/favicon.ico?v=4']
  }
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ReduxProvider>
      <LayoutProvider>
        {children}
        </LayoutProvider>
    </ReduxProvider>
  );
}
